---
title: "Making a Personal Website with GitHub and R"
output: 
  github_document:
    toc: true
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Making a Personal Website with GitHub and R
Much of this information is adapted from  [Nick Strayer and Lucy D'Agostino McGowan's tutorial](https://livefreeordichotomize.com/2017/08/08/how-to-make-an-rmarkdown-website/). 

## Make a GitHub Repository for the Website 

On your personal [GitHub](github.com), make a new repository that will correspond to (i.e., host) the personal website you are creating. Whatever you name this repository will show up in the main URL for your website, in the form "repositoryname.github.io", so you may want to make it your first and last name or something like that. Be sure to check the box for "intialize with a ReadMe", so that you can easily clone the repository to your computer. 

Follow the steps in our "Intro to Using Git and GitHub" tutorial to clone that repository and open it as an RStudio project. 

## Start 
test 2 to see if merge issue happens w/Jacob